export const validPrefixes = [
  'AA', 'AB', 'AC', 'AE', 'AG', 'AH', 'AJ', 'AK', 'AL', 'AM',
  'AN', 'AP', 'AR', 'AS', 'AT', 'AW', 'AX', 'AY', 'AZ', 'BA',
  'BB', 'BC', 'BE', 'BH', 'BJ', 'BK', 'BL', 'BM', 'BN', 'BP',
  'BR', 'BS', 'BT', 'BW', 'BX', 'BY', 'BZ', 'CA', 'CB', 'CC',
  'CE', 'CG', 'CH', 'CJ', 'CK', 'CL', 'CM', 'CN', 'CP', 'CR',
  'CS', 'CT', 'CW', 'CX', 'CY', 'CZ', 'EA', 'EB', 'EC', 'EE',
  'EG', 'EH', 'EJ', 'EK', 'EL', 'EM', 'EN', 'EP', 'ER', 'ES',
  'ET', 'EW', 'EX', 'EY', 'EZ', 'GA', 'GC', 'GE', 'GG', 'GH',
  'GJ', 'GK', 'GL', 'GM', 'GN', 'GP', 'GR', 'GS', 'GT', 'GW',
  'GX', 'GY', 'GZ', 'HA', 'HB', 'HC', 'HE', 'HG', 'HH', 'HJ',
  'HK', 'HL', 'HM', 'HN', 'HP', 'HR', 'HS', 'HT', 'HW', 'HX',
  'HY', 'HZ', 'JA', 'JB', 'JC', 'JE', 'JG', 'JH', 'JJ', 'JK',
  'JL', 'JM', 'JN', 'JP', 'JR', 'JS', 'JT', 'JW', 'JX', 'JY',
  'JZ', 'KA', 'KB', 'KC', 'KE', 'KG', 'KH', 'KJ', 'KK', 'KL',
  'KM', 'KP', 'KR', 'KS', 'KT', 'KW', 'KX', 'KY', 'KZ', 'LA',
  'LB', 'LC', 'LE', 'LG', 'LH', 'LJ', 'LK', 'LL', 'LM', 'LN',
  'LP', 'LR', 'LS', 'LT', 'LW', 'LX', 'LY', 'LZ', 'MA', 'MB',
  'MC', 'ME', 'MG', 'MH', 'MJ', 'MK', 'ML', 'MM', 'MN', 'MP',
  'MR', 'MS', 'MT', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NB', 'NC',
  'NE', 'NG', 'NH', 'NJ', 'NL', 'NM', 'NN', 'NP', 'NR', 'NS',
  'NW', 'NX', 'NY', 'NZ', 'OA', 'OB', 'OC', 'OE', 'OG', 'OH',
  'OJ', 'OK', 'OL', 'OM', 'ON', 'OP', 'OR', 'OS', 'OT', 'OW',
  'OX', 'OY', 'OZ', 'PA', 'PB', 'PC', 'PE', 'PG', 'PH', 'PJ',
  'PK', 'PL', 'PM', 'PN', 'PP', 'PR', 'PS', 'PT', 'PW', 'PX',
  'PY', 'PZ', 'RA', 'RB', 'RC', 'RE', 'RG', 'RH', 'RJ', 'RK',
  'RL', 'RM', 'RN', 'RP', 'RR', 'RS', 'RT', 'RW', 'RX', 'RY',
  'RZ', 'SA', 'SB', 'SC', 'SE', 'SG', 'SH', 'SJ', 'SK', 'SL',
  'SM', 'SN', 'SP', 'SR', 'SS', 'ST', 'SW', 'SX', 'SY', 'SZ',
  'TA', 'TB', 'TC', 'TE', 'TG', 'TH', 'TJ', 'TK', 'TL', 'TM',
  'TP', 'TR', 'TS', 'TT', 'TW', 'TX', 'TY', 'TZ', 'WA', 'WB',
  'WC', 'WE', 'WG', 'WH', 'WJ', 'WK', 'WL', 'WM', 'WN', 'WP',
  'WR', 'WS', 'WT', 'WW', 'WX', 'WY', 'WZ', 'XA', 'XB', 'XC',
  'XE', 'XG', 'XH', 'XJ', 'XK', 'XL', 'XM', 'XN', 'XP', 'XR',
  'XS', 'XT', 'XW', 'XX', 'XY', 'XZ', 'YA', 'YB', 'YC', 'YE',
  'YG', 'YH', 'YJ', 'YK', 'YL', 'YM', 'YN', 'YP', 'YR', 'YS',
  'YT', 'YW', 'YX', 'YY', 'YZ', 'ZA', 'ZB', 'ZC', 'ZE', 'ZG',
  'ZH', 'ZJ', 'ZK', 'ZL', 'ZM', 'ZN', 'ZP', 'ZR', 'ZS', 'ZT',
  'ZW', 'ZX', 'ZY'
]

export const validPrefixesObj = {
  AA: true,
  AB: true,
  AC: true,
  AE: true,
  AG: true,
  AH: true,
  AJ: true,
  AK: true,
  AL: true,
  AM: true,
  AN: true,
  AP: true,
  AR: true,
  AS: true,
  AT: true,
  AW: true,
  AX: true,
  AY: true,
  AZ: true,
  BA: true,
  BB: true,
  BC: true,
  BE: true,
  BH: true,
  BJ: true,
  BK: true,
  BL: true,
  BM: true,
  BN: true,
  BP: true,
  BR: true,
  BS: true,
  BT: true,
  BW: true,
  BX: true,
  BY: true,
  BZ: true,
  CA: true,
  CB: true,
  CC: true,
  CE: true,
  CG: true,
  CH: true,
  CJ: true,
  CK: true,
  CL: true,
  CM: true,
  CN: true,
  CP: true,
  CR: true,
  CS: true,
  CT: true,
  CW: true,
  CX: true,
  CY: true,
  CZ: true,
  EA: true,
  EB: true,
  EC: true,
  EE: true,
  EG: true,
  EH: true,
  EJ: true,
  EK: true,
  EL: true,
  EM: true,
  EN: true,
  EP: true,
  ER: true,
  ES: true,
  ET: true,
  EW: true,
  EX: true,
  EY: true,
  EZ: true,
  GA: true,
  GC: true,
  GE: true,
  GG: true,
  GH: true,
  GJ: true,
  GK: true,
  GL: true,
  GM: true,
  GN: true,
  GP: true,
  GR: true,
  GS: true,
  GT: true,
  GW: true,
  GX: true,
  GY: true,
  GZ: true,
  HA: true,
  HB: true,
  HC: true,
  HE: true,
  HG: true,
  HH: true,
  HJ: true,
  HK: true,
  HL: true,
  HM: true,
  HN: true,
  HP: true,
  HR: true,
  HS: true,
  HT: true,
  HW: true,
  HX: true,
  HY: true,
  HZ: true,
  JA: true,
  JB: true,
  JC: true,
  JE: true,
  JG: true,
  JH: true,
  JJ: true,
  JK: true,
  JL: true,
  JM: true,
  JN: true,
  JP: true,
  JR: true,
  JS: true,
  JT: true,
  JW: true,
  JX: true,
  JY: true,
  JZ: true,
  KA: true,
  KB: true,
  KC: true,
  KE: true,
  KG: true,
  KH: true,
  KJ: true,
  KK: true,
  KL: true,
  KM: true,
  KP: true,
  KR: true,
  KS: true,
  KT: true,
  KW: true,
  KX: true,
  KY: true,
  KZ: true,
  LA: true,
  LB: true,
  LC: true,
  LE: true,
  LG: true,
  LH: true,
  LJ: true,
  LK: true,
  LL: true,
  LM: true,
  LN: true,
  LP: true,
  LR: true,
  LS: true,
  LT: true,
  LW: true,
  LX: true,
  LY: true,
  LZ: true,
  MA: true,
  MB: true,
  MC: true,
  ME: true,
  MG: true,
  MH: true,
  MJ: true,
  MK: true,
  ML: true,
  MM: true,
  MN: true,
  MP: true,
  MR: true,
  MS: true,
  MT: true,
  MW: true,
  MX: true,
  MY: true,
  MZ: true,
  NA: true,
  NB: true,
  NC: true,
  NE: true,
  NG: true,
  NH: true,
  NJ: true,
  NL: true,
  NM: true,
  NN: true,
  NP: true,
  NR: true,
  NS: true,
  NW: true,
  NX: true,
  NY: true,
  NZ: true,
  OA: true,
  OB: true,
  OC: true,
  OE: true,
  OG: true,
  OH: true,
  OJ: true,
  OK: true,
  OL: true,
  OM: true,
  ON: true,
  OP: true,
  OR: true,
  OS: true,
  OT: true,
  OW: true,
  OX: true,
  OY: true,
  OZ: true,
  PA: true,
  PB: true,
  PC: true,
  PE: true,
  PG: true,
  PH: true,
  PJ: true,
  PK: true,
  PL: true,
  PM: true,
  PN: true,
  PP: true,
  PR: true,
  PS: true,
  PT: true,
  PW: true,
  PX: true,
  PY: true,
  PZ: true,
  RA: true,
  RB: true,
  RC: true,
  RE: true,
  RG: true,
  RH: true,
  RJ: true,
  RK: true,
  RL: true,
  RM: true,
  RN: true,
  RP: true,
  RR: true,
  RS: true,
  RT: true,
  RW: true,
  RX: true,
  RY: true,
  RZ: true,
  SA: true,
  SB: true,
  SC: true,
  SE: true,
  SG: true,
  SH: true,
  SJ: true,
  SK: true,
  SL: true,
  SM: true,
  SN: true,
  SP: true,
  SR: true,
  SS: true,
  ST: true,
  SW: true,
  SX: true,
  SY: true,
  SZ: true,
  TA: true,
  TB: true,
  TC: true,
  TE: true,
  TG: true,
  TH: true,
  TJ: true,
  TK: true,
  TL: true,
  TM: true,
  TP: true,
  TR: true,
  TS: true,
  TT: true,
  TW: true,
  TX: true,
  TY: true,
  TZ: true,
  WA: true,
  WB: true,
  WC: true,
  WE: true,
  WG: true,
  WH: true,
  WJ: true,
  WK: true,
  WL: true,
  WM: true,
  WN: true,
  WP: true,
  WR: true,
  WS: true,
  WT: true,
  WW: true,
  WX: true,
  WY: true,
  WZ: true,
  XA: true,
  XB: true,
  XC: true,
  XE: true,
  XG: true,
  XH: true,
  XJ: true,
  XK: true,
  XL: true,
  XM: true,
  XN: true,
  XP: true,
  XR: true,
  XS: true,
  XT: true,
  XW: true,
  XX: true,
  XY: true,
  XZ: true,
  YA: true,
  YB: true,
  YC: true,
  YE: true,
  YG: true,
  YH: true,
  YJ: true,
  YK: true,
  YL: true,
  YM: true,
  YN: true,
  YP: true,
  YR: true,
  YS: true,
  YT: true,
  YW: true,
  YX: true,
  YY: true,
  YZ: true,
  ZA: true,
  ZB: true,
  ZC: true,
  ZE: true,
  ZG: true,
  ZH: true,
  ZJ: true,
  ZK: true,
  ZL: true,
  ZM: true,
  ZN: true,
  ZP: true,
  ZR: true,
  ZS: true,
  ZT: true,
  ZW: true,
  ZX: true,
  ZY: true
}

export const validSuffixesObj = {
  A: true,
  B: true,
  C: true,
  D: true
}

export const validNumbersObj = {
  0: true,
  1: true,
  2: true,
  3: true,
  4: true,
  5: true,
  6: true,
  7: true,
  8: true,
  9: true
}

export const validSuffixes = ['A', 'B', 'C', 'D']

export const numberLength = 6
export const minNumber = 0
export const maxNumber = 999999
